name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm install
    - name: Build
      run: |
        npm run prod
        # gh-pages-spa
        sed '7i\'$'\n''<script src="/gh-pages-spa.js"></script>'$'\n' dist/patterns/index.html > dist/patterns/index-modified.html
        mv dist/patterns/index{-modified,}.html
      env:
        CI: true
    - name: Deploy
      if: success() && github.ref == 'refs/heads/master'
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./dist
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cname: uiengineering.de
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'

